services:
  - type: web
    name: chat-forum
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: TOKEN_SECRET
        generateValue: true
